# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [348]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [349]:
print(np.__version__)
print(np.show_config())


2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Kaan/anaconda3/Library/include
    lib directory: C:/Users/Kaan/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Kaan/anaconda3/Library/include
    lib directory: C:/Users/Kaan/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    name: cython


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [350]:
tensor_a = np.random.randint(0, 4, size=(2, 3, 5))
aa = np.random.rand(2, 3, 5)
tensor_a


array([[[1, 0, 3, 2, 1],
        [3, 3, 3, 0, 1],
        [1, 0, 0, 1, 3]],

       [[3, 0, 0, 2, 2],
        [0, 3, 3, 3, 3],
        [3, 2, 3, 2, 3]]], dtype=int32)


### 4. Print a.


In [351]:
print(aa)



[[[0.46463578 0.44471241 0.07295195 0.93080086 0.92637474]
  [0.38041789 0.4438563  0.67576499 0.46234932 0.11465827]
  [0.77961729 0.63469596 0.02859646 0.18737853 0.68414287]]

 [[0.68701921 0.27216915 0.23784086 0.58946087 0.44701351]
  [0.6424678  0.12633983 0.48054822 0.84980383 0.816714  ]
  [0.84406274 0.89078015 0.30359606 0.22441262 0.58731214]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [352]:
tensor_b = np.ones((5, 2, 3))



### 6. Print b.


In [353]:
print(tensor_b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [354]:

equal_result = (tensor_a.size == tensor_b.size)
print("Equality Comparison Result:")
print(equal_result)


Equality Comparison Result:
True



### 8. Are you able to add a and b? Why or why not?


In [355]:
#They have to be the same shape to add them




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [356]:
#tensor_a = 2 , 3, 5 
#tensor b = 5, 2, 3
tensor_c = np.transpose(tensor_b, (1 , 2, 0))
print(tensor_c.shape)


(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [357]:
tensor_d = tensor_a + tensor_c
print(tensor_d)


[[[2. 1. 4. 3. 2.]
  [4. 4. 4. 1. 2.]
  [2. 1. 1. 2. 4.]]

 [[4. 1. 1. 3. 3.]
  [1. 4. 4. 4. 4.]
  [4. 3. 4. 3. 4.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [358]:
print(tensor_a)
print(tensor_d)



[[[1 0 3 2 1]
  [3 3 3 0 1]
  [1 0 0 1 3]]

 [[3 0 0 2 2]
  [0 3 3 3 3]
  [3 2 3 2 3]]]
[[[2. 1. 4. 3. 2.]
  [4. 4. 4. 1. 2.]
  [2. 1. 1. 2. 4.]]

 [[4. 1. 1. 3. 3.]
  [1. 4. 4. 4. 4.]
  [4. 3. 4. 3. 4.]]]



### 12. Multiply a and c. Assign the result to e.


In [359]:
tensor_e = tensor_a*tensor_c



### 13. Does e equal to a? Why or why not?


In [360]:
#yes because we multiplied by one





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [361]:
d_max = np.max(tensor_d)
d_min = np.min(tensor_d)
d_mean = np.mean(tensor_d)
print(d_max)
print(d_min)
print(d_mean)


4.0
1.0
2.8



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [362]:
f = np.empty((2 ,3 ,5 ), dtype = object)
f


array([[[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]]], dtype=object)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [363]:
con_25 = (tensor_d > d_min) & (tensor_d < d_mean)
con_75 = (tensor_d > d_mean) & (tensor_d < d_max)
con_50 = (tensor_d == d_mean) 
con_0 = (tensor_d == d_min)
con_100 = (tensor_d == d_max)
f[con_25] = 25
f[con_75] = 75
f[con_50] = 50
f[con_0] = 0
f[con_100] = 100
f



array([[[25, 0, 100, 75, 25],
        [100, 100, 100, 0, 25],
        [25, 0, 0, 25, 100]],

       [[100, 0, 0, 75, 75],
        [0, 100, 100, 100, 100],
        [100, 75, 100, 75, 100]]], dtype=object)





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [364]:
print(d)
print(f)


[[[1. 1. 3. 1. 3.]
  [4. 1. 4. 2. 3.]
  [3. 1. 3. 4. 4.]]

 [[3. 2. 4. 3. 1.]
  [2. 4. 4. 4. 3.]
  [4. 3. 2. 2. 1.]]]
[[[25 0 100 75 25]
  [100 100 100 0 25]
  [25 0 0 25 100]]

 [[100 0 0 75 75]
  [0 100 100 100 100]
  [100 75 100 75 100]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [365]:
con_25 = (tensor_d > d_min) & (tensor_d < d_mean)
con_75 = (tensor_d > d_mean) & (tensor_d < d_max)
con_50 = (tensor_d == d_mean) 
con_0 = (tensor_d == d_min)
con_100 = (tensor_d == d_max)
f[con_25] = 'A'
f[con_75] = "B"
f[con_50] = "C"
f[con_0] = "D"
f[con_100] = "E"
f

array([[['A', 'D', 'E', 'B', 'A'],
        ['E', 'E', 'E', 'D', 'A'],
        ['A', 'D', 'D', 'A', 'E']],

       [['E', 'D', 'D', 'B', 'B'],
        ['D', 'E', 'E', 'E', 'E'],
        ['E', 'B', 'E', 'B', 'E']]], dtype=object)